### ISSUE TITLE
Would it be nice to add notifications to xpassmenu?

### ISSUE THREAD

**Issue by boogie666** [uluyol/xmenu#3]
Hello,

I just came across this:

```
osascript -e "display notification \"$password has been copied to clipboard\" with title \"xpassmenu\""
```

I think it goes well in xpassmenu. should i add it in? 

(it displays a notification that the selected password has been copied to clipboard)

**Comment by uluyol** [comment]
I normally don't like when programs point out the obvious. Since this is password copying though, a little paranoia is probably OK.

This change sounds good to me.

**Comment by boogie666** [comment]
I'll add it and submit a PR soon, cheers.
